let nhl = [{
	"city": "Anaheim",
	"name": "Ducks",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/1736/full/1651_anaheim_ducks-primary-2014.gif"
}, {
	"city": "Arizona"
	"name": "Coyotes",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/5263/full/7807_arizona_coyotes-primary-2015.png"
}, {
	"city": "Boston",
	"name": "Bruins",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/3/full/venf9fmhgnsawnxxvehf.png"
}, {
	"city": "Buffalo",
	"name": "Sabres",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/4/full/i40oxcdbo7xtfamqqhqachoyo.png"
}, {
	"city": "Calgary",
	"name": "Flames",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/5/full/50.png"
}, {
	"city": "Carolina",
	"name": "Hurricanes",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/6/full/fotih31tn5r345nufo5xxayh3.png"
}, {
	"city": "Chicago",
	"name": "Blackhawks",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/7/full/56.png"
}, {
	"city": "Colorado",
	"name": "Avalanche",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/8/full/64.png"
}, {
	"city": "Columbus",
	"name": "Blue Jackets",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/9/full/jhepegs329pc7ugyypebl28wg.png"
}, {
	"city": "Dallas",
	"name": "Stars",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/10/full/7917_dallas_stars-primary-2014.png"
}, {
	"city": "Detroit",
	"name": "Red Wings",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/11/full/yo3wysbjtagzmwj37tb11u0fh.png"
}, {
	"city": "Edmonton",
	"name": "Oilers",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/12/full/6cphie5heyvfwn6lbzfowe61h.png"
}, {
	"city": "Florida",
	"name": "Panthers",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/13/full/8078_florida_panthers-primary-2017.png"
}, {
	"city": "Los Angeles",
	"name": "Kings",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/14/full/71jepx81eqzz1l6q9g1g5j1lh.png"
}, {
	"city": "Minnesota",
	"name": "Wild",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/15/full/8810_minnesota_wild-primary-2014.png"
}, {
	"city": "Montreal",
	"name": "Canadiens",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/16/full/124.png"
}, {
	"city": "Nashville",
	"name": "Predators",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/17/full/lvchw3qfsun2e7oc02kh2zxb6.png"
}, {
	"city": "New Jersey",
	"name": "Devils",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/18/full/32tfs723a3bes0p0hb4hgcy1u.png"
}, {
	"city": "New York",
	"name": "Islanders",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/19/full/79520qbne58r9i71zhuggbff0.png"
}, {
	"city": "New York",
	"name": "Rangers",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/20/full/144.png"
}, {
	"city": "Ottawa",
	"name": "Senators",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/21/full/2bkf2l3xyxi5p0cavbj8.png"
}, {
	"city": "Philadelphia",
	"name": "Flyers",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/22/full/161.png"
}, {
	"city": "Pittsburgh",
	"name": "Penguins",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/24/full/6362_pittsburgh_penguins-primary-2017.png"
}, {
	"city": "San Jose",
	"name": "Sharks",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/26/full/dmo1xf3z4pph27vmg3gf.png"
}, {
	"city": "St. Louis",
	"name": "Blues",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/25/full/187.png"
}, {
	"city": "Tampa Bay",
	"name": "Lightning",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/27/full/97hhvk8e5if0riesnex30etgz.png"
}, {
	"city": "Toronto",
	"name": "Maple Leafs",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/28/full/8761_toronto_maple_leafs-primary-2017.png"
}, {
	"city": "Vancouver",
	"name": "Canucks",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/29/full/tlxz9higxwygaehl0j5h.png"
}, {
	"city": "Las Vagas",
	"name": "Golden Knights",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/6114/full/2684_vegas_golden_knights-primary-2018.png"
} {
	"city": "Washington",
	"name": "Capitals",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/30/full/llrs2zxi127vkqgcsvfb.png"
}, {
	"city": "Winnipeg",
	"name": "Jets",
	"sport": "Hockey",
	"logo_url": "http://content.sportslogos.net/logos/1/3050/full/z9qyy9xqoxfjn0njxgzoy2rwk.png"
}]